name: Upload SARIF Results

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [main]  # Runs on push to main

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/scan-results.sarif
