name: Dependency Vulnerability Scan

on:
  push:
    branches:
      - master

jobs:
  dependency-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Dependency-Check
        uses: dependency-check/action@v3.0.0
        with:
          project: 'MyProject'
          path: '.'
          format: 'HTML'
          failOnCVSS: '7.0'

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html
