name: OWASP Dependency Check
on:
  push:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Dependency Check
        uses: jpwright/dependency-check-action@v3
        with:
          arguments: >
            --project "Secure Pipeline Demo"
            --scan .

